version: '3.1'

services:
  ms_calculator:
    image: golang
    working_dir: "/usr/current/app"
    command: ./entrypoint.sh
    env_file: .env
    volumes:
      - .:/usr/current/app:rw
    ports: [ "50051:50051" ]
    networks: [ starter-net ]

networks:
  starter-net:
    name: starter-net